ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"
  autofix_prs: true
  autoupdate_schedule: weekly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-toml
      - id: check-json
      - id: debug-statements
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.14.10"
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
      - id: ruff-format

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: "v0.47.0"
    hooks:
      - id: markdownlint-fix
        args: ["--config", ".markdownlint.json"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.19.1"
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML
          - types-tqdm
        args: [--ignore-missing-imports]
        exclude: ^(tests/|scripts/)

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: python
        pass_filenames: false
        always_run: true
        args: ["-x", "--tb=short", "-q", "tests/unit"]
        stages: [pre-push]
        additional_dependencies:
          - pytest
